# Generated by Django 5.2.4 on 2025-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ship_name', models.CharField(max_length=200)),
                ('ship_country', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
